language: centos
jobs:
  include:
  - stage: Tests
    script: ".travis/ci"
  - stage: deploy
    if: branch = master
    script: ".travis/deploy"
env:
  global:
    secure: mquWTKhcAw7TAO11qWWLeN3J1UHGjyCoR2nJYThQYfAUFJbadqMn0KhLMSeKYeCClvoXx4YaZIb8uDzI1CIvb4y2pNp7zWJsmfwS6Rdii221e3CVI+7ZTo88fYSSe6Cunmq5Ftf/oqpUrtipKeRjPjwXo2S+WNfn+GFdm+vytGwHQJ70Io33lMghMTn5OXnMq6pa3K1lX/si68deo8izEk/b3pcMh0hLSulV2jGamldEFOoe3OMioT73iaJPgiwQnmP17KPfe7tzC5UowApPwB5OP92D5ltTv91sprQ7maRHCGhoNJ3c8gxgNganUKhWT2AkGW3OmLeE9VUYcSugBeNfcHppa7zZSJuIeZdCjRRKEutFDJAk+RDhxC5v861PirfWarogZqeL9m5xznBgGNQXvu92AlaiI/AbcnWdkmWpFRVrmCqRo96HzRJDJ5j79NwzFQgi8u6mj0D+nsRV5o+Wyh/7HcjspxZHRrLGYzCDw/5BiDwRVaSz+ofgK9qbIVAiI/XrMa87ZsZzVhHi5hDtG7JJxuThK7o7xFnHYPODdSZN8TWYtNK1PsygwY4kyoPthK1uM048lqv4KWqhYkMH3/lOJOCrc34bHfvYUjemL7aBdhcWe0WBKzWXk7xwk1D2hCes9D0DejJoKnZGqRF5s6/B8M+lv/adVeytOSo=
