before_install:
- openssl aes-256-cbc -K $encrypted_395a8489d4c6_key -iv $encrypted_395a8489d4c6_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- sudo apt-get update -q
- sudo apt-get -qqy install curl sudo
jobs:
  include:
  - stage: Tests
    script: ".travis/ci"
addons:
  ssh_known_hosts: dark-hitoyoshi-1876@ssh-1.mc.lolipop.jp:35279
deploy:
  provider: script
  skip_cleanup: true
  script: bash .travis/deploy
  on:
    branch: master
