before_install:
- sudo apt-get update -q
- sudo apt-get -qqy install curl sudo
jobs:
  include:
  - stage: Tests
    script: ".travis/ci"
addons:
  ssh_known_hosts: dark-hitoyoshi-1876@ssh-1.mc.lolipop.jp:35279
deploy:
  provider: script
  skip_cleanup: true
  script: bash .travis/deploy
  on:
    branch: master
notifications:
  slack: pepabo:CQkcN0cdvPSJvVsK2D48qYyV
