language: centos
jobs:
  include:
  - stage: Tests
    name: Unit Tests
    script: true
  - stage: deploy
    if: branch = master
    name: Deploy to GCP
    script: "./deploy"
env:
  global:
    secure: RYDn9p6jDLwGSzqFtyVQ2RBHgYL9ql31t5uMUKaqB3aSKulwXNjaDj5MRxXXgJA3FL4lNkzsF57MSH47+DGuDCMug7XJ8/9BchkxcbXdknrMCbId4oCGKlBid2YKL8ooye+8Nt6jPevK+iuunEpmPMhXFLsayAKG8PT41L+gwdKqohq+l6f5huSTlExn3E5ddWEFOr4gzcFxHlBOPVtRHa2ww9A3xmZ1pKYES1fbrOgDs0t5TBwDyH45L0SToG86SF13RSTZo5t4HviwZ3uKD4MGuaa6hgCZeRPYnPAUWG96b+RWxisFbI5BRSF1LjO2OpC+gUuerDPFiBLHJeQZYlScT66TVwwGSXWglDNlnS4ER+bSBdm5ue/2t3S4ZPKpDHp4q9xDam7d3TjbYZ4woLSYB1NPzogjjQWlwCRgqn/vyngcMme2jYB/mU1EN9cTP/m8yLmc7dK5iSGgpinZPxOKdYgrcbcTveWu1XVPY5AiB2YOpbrMtNYHMjHvOeSRJQyDFK+NuKBMTMhB7DnZDU6vJeIRySMSIVYjQj0/8rrnM+yQO+JsxPEqsZ2QFAKPM9scOPtbWAbfUm/nUD94ACcFRqoIM27z6n2p9WyH8//Yo2RKSoXgkov9JjRw9xyQUTcDjHQ3O23YD+Q8phgvQd0pWY4jKjVyB31X0cfWbL4=
