before_install:
- openssl aes-256-cbc -K $encrypted_395a8489d4c6_key -iv $encrypted_395a8489d4c6_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- sudo apt-get update -q
- sudo apt-get -qqy install curl sudo
jobs:
  include:
  - stage: Tests
    script: ".travis/ci"
deploy:
  provider: script
  script: bash .travis/deploy
  on:
    branch: master
