before_install:
- sudo apt-get update -q
- sudo apt-get -qqy install curl sudo
jobs:
  include:
  - stage: Tests
    script: ".travis/ci"
deploy:
  provider: script
  script: bash .travis/deploy
  on:
    branch: master
