before_install:
- sudo apt-get update -q
- sudo apt-get -qqy install curl sudo
jobs:
  include:
  - stage: Tests
    script: ".travis/ci"
addons:
  ssh_known_hosts: dark-hitoyoshi-1876@ssh-1.mc.lolipop.jp
before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: bash .travis/deploy
  on:
    branch: master
