#!/bin/bash
set -e -x
cp /tmp/deploy_rsa ~/.ssh/
chmod 600 ~/.ssh/deploy_rsa
for n in stns users groups
do
  scp -o StrictHostKeyChecking=no -i ~/.ssh/deploy_rsa -P 35279 $n.conf dark-hitoyoshi-1876@ssh-1.mc.lolipop.jp:/var/app
done
