#!/bin/bash
set -e -x
openssl aes-256-cbc -K $encrypted_395a8489d4c6_key -iv $encrypted_395a8489d4c6_iv -in deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
chmod 600 ~/.ssh/deploy_rsa
for n in stns users groups
do
  scp -o StrictHostKeyChecking=no -i ~/.ssh/deploy_rsa -P 35279 $n.conf dark-hitoyoshi-1876@ssh-1.mc.lolipop.jp:/var/app
done
